### ISSUE TITLE
是不是可以提供一个 Demo 项目

### ISSUE THREAD

**Issue by WangLaoShi** [w4o/xx#1]
麻烦能提供一个 Demo 项目吗？

期望：

1. 本项目的使用规范
2. 如何实现一个小型的Demo，例如经典的 [PetsShop](https://www.oracle.com/java/technologies/petstore-v1312.html) 或者 [MyPetsShop](https://github.com/Shivanihumber/MyPetShop)
3. 是否可以提供一个项目的生成向导，例如，我提供给你了数据库的链接信息，能帮助我生成一个项目的骨架。包含基础的 CURD 操作

**Comment by w4o** [comment]
欢迎PR

**Comment by WangLaoShi** [comment]
谢谢给出的demo 项目：https://github.com/w4o/xx-admin
